[project]
name = "ancillary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mystmd>=1.3.28",
    "pillow>=11.2.1",
    "qrcode>=8.2",
]
